#!/bin/bash
#########################################
##### Exemplo de particionamento ########
#########################################
# cfdisk /dev/sda
# raiz: /                   /dev/sda1
# home: /home               /dev/sda2
# swap:  swap               /dev/sda3
#########################################
### Formatar a partição raiz /
#
# mkfs.ext4 /dev/sda1
#
## Formatar a partição /home
#
# mkfs.ext4 /dev/sda2
#
## Preparando a partição swap
#
# mkswap /dev/sda3 && swapon /dev/sda3
#
## Montar a partição raiz em /mnt
#
# mount /dev/sda1 /mnt
#
## Montar a partição home
#
# mkdir /mnt/home && mount /dev/sda2
########################################

# Configure as partições do HD

# Configuração do Teclado
echo "Configurando teclado para pt_BR"
loadkeys br-abnt2

##########################################################
############### Configurando a Rede - DNS ################
##########################################################
echo "Configurando DNS"
chattr -i /etc/resolv.conf
sed -i '1,10d' /etc/resolv.conf | more
su -c "echo 'domain google.com' >> /etc/resolv.conf"
su -c "echo 'search google.com store.steampowered.com' >> /etc/resolv.conf"
su -c "echo 'nameserver 8.8.8.8' >> /etc/resolv.conf"
su -c "echo 'nameserver 8.8.4.4' >> /etc/resolv.conf"
chattr +i /etc/resolv.conf
echo "DNS Configurado"
##########################################################
################ Instalação do Sistema ###################
##########################################################
echo "Instalando o Sistema Básico"
# Usando o script pacstrap instalamos os pacotes do grupo base e base-devel:

pacstrap /mnt base base-devel

# Criando o fstab
echo "Criando o fstab"
# Aguarda 2 segundos
sleep 2

genfstab -U -p /mnt >> /mnt/etc/fstab

# Chroot e outras configurações
# Chroot é o comando usado para irmos até a raiz de outro diretório. Até então estamos no Live-CD, mas agora iremos para o sistema instalado no HD. Execute: 

# Aguarda 2 segundos
sleep 2

arch-chroot /mnt /bin/bash

# Agora você está no seu sistema Arch Linux propriamente. 
# Primeiro vamos configurar o idioma. Precisaremos alterar dois arquivos: locale.gen e locale.conf. 
# Abra o locale.gen: 
# Removemos o # da frente das seguintes linhas: pt_BR.UTF-8 UTF-8 e pt_BR ISO-8859-1
echo "Configurando locale.gen"
# Aguarda 2 segundos
sleep 2

sed -i '/pt_BR/s/^#//' /etc/locale.gen

# Depois executamos:

# Aguarda 2 segundos
sleep 2

locale-gen

# Agora definimos o idioma padrão do sistema criando ao mesmo tempo o arquivo locale.conf: 
echo "Definindo o idioma padrão para português do Brasil" 
# Aguarda 2 segundos
sleep 2
echo LANG=pt_BR.UTF-8 > /etc/locale.conf 
export LANG=pt_BR.UTF-8 

# No início do processo configuramos o teclado, mas estávamos no Live-CD. Agora configure o teclado no sistema recém instalado: 

loadkeys br-abnt2 

# Configuramos a zona de tempo: 
echo "Configurando Zona do tempo (localtime) para América Recife"
# Aguarda 2 segundos
sleep 2
ln -s /usr/share/zoneinfo/America/Recife /etc/localtime 2> /dev/null

# Usei America/Recife. No seu caso pode ser diferente. Para ver as opções disponíveis use o comando: 
# ls /usr/share/zoneinfo/ 

# Configuração do relógio em UTC: 

# Aguarda 2 segundos
sleep 2

hwclock --systohc --utc 

# Defina o nome da máquina: 

echo arch > /etc/hostname 

# Por exemplo, pode-se usar "arch" ou "archlinux" ou o modelo do computador como "toshiba-is-1412". Você decide. Não use aspas. 

# Configuração de Rede no Sistema Instalado

systemctl enable dhcpcd@enp0s1.service

# Instalação de alguns pacotes necessários para conexão a internet via wifi

pacman -S wireless_tools wpa_supplicant wpa_actiond dialog -y

# Após isso, habilite o serviço de conexão automática: 

# systemctl enable net-auto-wired.service 

############################################################
# Configuração do Pacman, senha de root e criação de usuário
############################################################

############################################################
####################### Multilib ###########################
mv pacman.conf /etc/
############################################################
################### Saindo do Script #######################
exit
############################################################
############################################################

